# Generated by Django 3.1.4 on 2020-12-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201215_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('staff_member_required', 'View all borrowed books'))},
        ),
    ]
